title: JSON Quiz
description: A specification for building quizzes in JSON
baseurl: /json-quiz
exclude: [build, node_modules, README.md]
markdown: kramdown
kramdown:
  input: GFM
collections:
  spec:
    output: true
gems:
  - jekyll-redirect-from