title: JSON Quiz
description: A specification for building quizzes in JSON
baseurl: /quiz-format
exclude: [build, node_modules]
markdown: kramdown
kramdown:
  input: GFM
collections:
  spec:
    output: true
